"""empty message

Revision ID: c711379f0f0f
Revises: b38bcfd608b1
Create Date: 2022-08-04 13:02:08.230285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c711379f0f0f'
down_revision = 'b38bcfd608b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'email2')
    # ### end Alembic commands ###
